version: '3.8'

services:
  frontend:
    build:
      context: ./app # Le chemin vers le dossier Next.js
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - payload
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CAPTCHA_SITE_KEY=${NEXT_PUBLIC_CAPTCHA_SITE_KEY}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./app:/app # Montez le répertoire local dans le conteneur

  payload:
    image: node:18-alpine
    ports:
      - '4000:3000'
    volumes:
      - ./backoffice:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
